# Site settings
title: My Creations
email: gay.carson.andrew@gmail.com
description: A small blog with all of my creations
baseurl: "/gay-carson-andrew.github.io"
url: "gay-carson-andrew.github.io"
twitter_username: 
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Andrew Carson Gay" # Set default author name
      categories: "general"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
